name: Build and Publish documentation

on:
  create:
    tags:
      - v*
  push:
    branches:
      - 'refs/tags/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: build
      run: |
        pip3 install setuptools wheel
        python3 setup.py build
        python3 setup.py bdist_wheel
    - name: pypi-publish
      uses: pypa/gh-action-pypi-publish@v1.3.1
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
